# Generated by Django 5.2.7 on 2025-10-15 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'giftcards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderGiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('giftcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftcard.giftcard')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'order_giftcards',
                'unique_together': {('order', 'giftcard')},
            },
        ),
        migrations.AddField(
            model_name='giftcard',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='giftcards', through='giftcard.OrderGiftCard', through_fields=('giftcard', 'order'), to='order.order'),
        ),
    ]
