# Generated by Django 5.2.7 on 2025-10-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordergiftcard',
            options={'ordering': ['-used_at']},
        ),
        migrations.AlterUniqueTogether(
            name='ordergiftcard',
            unique_together=set(),
        ),
    ]
